#! /usr/bin/perl
use strict;

my $conta;
my @contb;
my $contc;

$conta = `ls -1d lcn/*.json | sort`;
@contb = split(/\n/,$conta);
foreach $contc (@contb)
{
  system("echo","-n",($contc . ': '));
  system("languamunity","agri","-f",$contc,"-cnt");
}

