#! /usr/bin/perl
use strict;
use File::Basename;
use Cwd 'realpath';

my $pre_minim = 50;

my $minim;
my $ourdir;
my $avail;
my $ourlcn;
my $ourlcsh;
my $ourscrat;
my $thisnow;

$thisnow = `date +%s`; chomp($thisnow);


($ourlcn,$minim) = @ARGV;
if ( $minim eq '' ) { $minim = $pre_minim; }
if ( $ourlcn eq '' )
{
  die "\nNo lesson specified - that is a deal-breaker.\n\n";
}

$ourdir = dirname(dirname(realpath($0)));
$ourlcsh = $ourdir . '/comres/sh/lcn-' . $ourlcn . '.sh';
if ( !(-f $ourlcsh) )
{
  die ("\nNo such lesson: " . $ourlcn . ":\n" .
    "  (Unrepresented at " . $ourlcsh . ")\n" .
  "\n");
}
$ourscrat = $ourdir . '/scratch/at-' . $thisnow;
{
  my $lc_a;
  my @lc_b;
  my $lc_c;
  my $lc_d;
  my $lc_e;
  $ENV{"LANGDRILL_X_SUSCRAT"} = ($ourdir . '/scratch');
  $lc_a = `cat \"\${LANGDRILL_X_SUSCRAT}\"`;
  @lc_b = split(/\n/,$lc_a);
  foreach $lc_c (@lc_b)
  {
    ($lc_d,$lc_e) = split(quotemeta('-'),$lc_c);
    if ( $lc_d eq 'at' )
    {
      if ( ( $thisnow - $lc_e ) > ( 60 * 10 ) )
      {
        system("echo","rm","-rf",($ourdir . '/scratch/' . $lc_c));
      }
    }
  }
}

system("languamunity","clear-names");
system("languamunity","lc-take",($ourdir . "/res/names.json"));

sub check_avail {
  my $lc_avail;
  $lc_avail = `languamunity statlli deck+hand`;
  chomp($lc_avail);
  $avail = $lc_avail;
  return $lc_avail;
}

$ENV{"LANGDRILL_X_OURDIR"} = $ourdir;
$ENV{"LANGDRILL_X_LCDIR"} = ($ourdir . '/lcn');
$ENV{"LANGDRILL_X_SCRAT"} = $ourscrat;

while ( &check_avail() < ( $minim - 0.5 ) )
{
  system("mkdir","-p",$ourscrat);
  system("sh",($ourdir . '/comres/sh/lcn-' . $ourlcn . '.sh'));
  system("rm","-rf",$ourscrat);
  system("echo","Loading: " . $avail);
  sleep(1);
}
exec("perl",($ourdir . "/com/resume"));






